import turtle
star=turtle.Turtle()
star.begin_fill()
star.fillcolor("yellow")
star.speed(1)
ashu = turtle.Screen()
ashu.bgcolor("Black")
star.circle(100,steps=3)
star.color("white","yellow")
star.circle(100,steps=3)
star.up()
star.goto(0,1.762*100)
star.down()
star.fillcolor("yellow")
star.circle(-100,steps=3)
star.end_fill()